project:
  type: website

website:
  title: "blognils"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/NilsBiller
        
format:
  html:
    toc: true
    df-print: paged
    theme: darkly
    css: styles.css

editor: visual

